version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3"

formats: all

python:
  install:
    - requirements: docs/requirements-rtd.txt

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
