name: Build/Publish Docker Hub Image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_push_docker_image:
    name: Build/push image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}

      - name: Build and push Docker image
        if: github.repository == 'gboeing/osmnx'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./environments/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
