name: Publish Python distribution to PyPI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build and publish on PyPI
    environment:
      name: testpypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Build and check package
      run: |
        python -m pip install hatch twine --user
        python -m hatch build --clean
        python -m twine check --strict ./dist/*

    - name: Publish distribution
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        print-hash: true
        verbose: true
        verify-metadata: true
