# This workflow runs the test suite using the minimum supported dependency
# versions.
name: Test minimum dependencies

on:
  schedule:
    - cron: 20 4 * * 1  # every monday at 04:20 UTC
  workflow_dispatch:

jobs:
  test_minimum_deps:
    if: ${{ github.repository == 'gboeing/osmnx' }}
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    defaults:
      run:
        shell: bash -elo pipefail {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: pyproject.toml

      - name: Install OSMnx with minimum dependency versions
        run: |
          uv export --all-extras --no-group=dev --resolution=lowest-direct --no-hashes --no-header --no-annotate --no-build --python=3.9 > requirements.txt
          uv export --only-dev --resolution=highest --no-hashes --no-header --no-annotate --no-build --python=3.9 > requirements-dev.txt
          uv venv --python=3.9
          source .venv/bin/activate
          uv pip install --requirements requirements.txt --python=3.9
          uv pip install --requirements requirements-dev.txt --python=3.9
          uv run python --version
          uv pip show osmnx
          uv pip list

      - name: Test code
        run: uv run pytest --verbose --maxfail=1 --numprocesses=3 --dist=loadgroup
