name: Build and check package/docs

on:
  schedule:
    - cron: "0 6 * * 1" # every monday at 06:00 UTC
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    defaults:
      run:
        shell: bash -elo pipefail {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install requirements
        run: python -m pip install -r ./environments/tests/requirements-test-build.txt

      - name: Build and validate package
        run: |
          validate-pyproject ./pyproject.toml
          hatch build --clean
          twine check --strict ./dist/*

      - name: Build docs and check links
        run: python -m sphinx -E -W --keep-going -b linkcheck ./docs/source ./docs/build/linkcheck
