# This workflow runs the test suite using the latest/pre-release dependency
# versions.
name: Test latest/pre-release dependencies

on:
  schedule:
    - cron: 30 4 * * 1  # every monday at 04:30 UTC
  workflow_dispatch:

jobs:
  test_latest_deps:
    if: ${{ github.repository == 'gboeing/osmnx' }}
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    defaults:
      run:
        shell: bash -elo pipefail {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.*

      - name: Install OSMnx with latest/pre-release dependencies
        run: |
          uv sync --all-extras --group=tests --prerelease=allow
          uv pip check
          uv pip list
          uv pip show osmnx
          uv run python --version

      - name: Test code
        run: uv run pytest --verbose --maxfail=1
