name: Build docs and check links

on:
  schedule:
    - cron: "30 4 * * 1" # every monday at 04:30 UTC
  workflow_dispatch:

jobs:
  test_docs_linkcheck:
    if: ${{ github.repository == 'gboeing/osmnx' }}
    name: Build docs and check links
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -elo pipefail {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install requirements
        run: |
          python -m pip install --user furo "sphinx==7.*" sphinx-autodoc-typehints
          python -m pip check

      - name: Build docs and check links
        run: python -m sphinx -E -W --keep-going -b linkcheck ./docs/source ./docs/build/linkcheck
