# This workflow runs the test suite using the minimum supported dependency
# versions.
name: Test minimum dependencies

on:
  schedule:
    - cron: 20 4 * * 1  # every monday at 04:20 UTC
  workflow_dispatch:

jobs:
  test_minimum_deps:
    if: ${{ github.repository == 'gboeing/osmnx' }}
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ['3.9']

    defaults:
      run:
        shell: bash -elo pipefail {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          cache-dependency-glob: pyproject.toml
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install OSMnx with minimum dependency versions
        run: |
          uv export --no-build --all-extras --no-dev --resolution=lowest-direct > reqs.txt
          uv export --no-build --only-dev --resolution=highest > reqs-dev.txt
          uv pip install --requirements reqs.txt
          uv pip install --requirements reqs-dev.txt
          uv run python --version
          uv pip show osmnx
          uv pip list

      - name: Test code
        run: uv run pytest --verbose --maxfail=1 --numprocesses=3 --dist=loadgroup
